# tasks/main.yml
---
- name: Ensure PPA dependencies are installed
  ansible.builtin.apt:
    name: "{{ php_ppa_dependencies }}"
    state: present
    update_cache: true
  when: ansible_distribution == "Ubuntu"

- name: Check if PHP PPA source list file exists
  ansible.builtin.stat:
    path: "{{ php_source_list_file }}"
  register: php_ppa_file

- name: Add Ondrej PHP PPA using add-apt-repository
  ansible.builtin.command: add-apt-repository -y {{ php_repo }}
  environment:
    LC_ALL: C.UTF-8
  changed_when: false
  when:
    - ansible_distribution == "Ubuntu"
    - not php_ppa_file.stat.exists

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  when: ansible_distribution == "Ubuntu"

- name: Build PHP package list
  ansible.builtin.set_fact:
    php_packages: "{{ php_base_packages + php_extensions | map('regex_replace', '^(.*)$', 'php' ~ php_version ~ '-\\1') | list }}"

- name: Install php packages
  ansible.builtin.apt:
    name: "{{ php_packages }}"
    state: present
    update_cache: true
  when: php_packages | length > 0
