# molecule/default/vars/all.yml
---
php_ppa_dependencies:
  - software-properties-common
  - gnupg
  - gpg-agent

php_repo: ondrej/php

php_version: "5.6"

php_base_packages:
  - php-pear
  - php-php-gettext

php_extensions:
  - bcmath
  - curl
  - dev
  - gd
  - gmp
  - igbinary
  - imagick
  - mbstring
  - mcrypt
  - mysql
  - redis
  - soap
  - xdebug
  - xml
  - xmlrpc
  - yaml
  - zip

php_ini_sapi_configs:
  - sapi: apache2
    disable_functions:
      - pcntl_alarm
      - pcntl_fork
    expose_php: "Off"
    memory_limit: 128M

  - sapi: cli
    disable_functions: ""
    expose_php: "On"
    memory_limit: "-1"

php_phing_file: /usr/local/bin/phing
